baseurl: ''
exclude: ['README.md']
permalink: pretty
title: 'Wisdom Foundation'
email: 'admission@wisdomfoundation.in'

collections:
  courses:
    output: true
    permalink: /courses/:path/
  posts:
    output: true
    permalink: /posts/:path/
  team:
    output: true
    permalink: /team/:path/
  testimonials:
    output: true
    permalink: /testimonials/:path/


defaults:
  - scope:
      type: courses
    values:
      layout: service
      bodyClass: page-services-single
  - scope:
      path: 'images'
    values:
      image: true

sass:
  style: compact # possible values: nested expanded compact compressed

google_analytics_id: null

plugins:
  - jekyll-paginate
  - jekyll-environment-variables
